---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-b
  labels:
    app.kubernetes.io/name: test-b
    app.kubernetes.io/version: ${RELEASE}
    app.kubernetes.io/component: http
    app.kubernetes.io/part-of: pnpm-monorepo
    app.kubernetes.io/managed-by: github-actions
data:
  NODE_ENV: production
