name: Job matrices
description: Get job matrices for changed packages
inputs:
  packages:
    description: Comma-separated list of changed packages
    required: true
outputs:
  matrices:
    description: A json object representing which packages each job should be run for
runs:
  using: node16
  main: index.js
