on:
  push:
    branches:
      - "**"

jobs:
  call_reusable_workflow:
    name: Shared
    uses: chiel/ci/.github/workflows/monorepo.yaml@master
    with:
      publish_author_name: Chiel Kunkels
      publish_author_email: chiel@kunkels.me
    secrets:
      github_pat: ${{ secrets.GITHUB_TOKEN }}
